<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\StockPortfolio.Modules.MarketData.Application\StockPortfolio.Modules.MarketData.Application.csproj" />
    <ProjectReference Include="..\..\..\Shared.Presentation\StockPortfolio.Shared.Presentation.csproj" />
  </ItemGroup>

</Project>
