<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Identity.Stores" />
    <PackageReference Include="OneOf" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Shared.Kernel\StockPortfolio.Shared.Kernel.csproj" />
  </ItemGroup>

</Project>
