<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="OneOf" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\StockPortfolio.Modules.Alerts.Domain\StockPortfolio.Modules.Alerts.Domain.csproj" />
    <ProjectReference Include="..\StockPortfolio.Modules.Alerts.Contracts\StockPortfolio.Modules.Alerts.Contracts.csproj" />
  </ItemGroup>

</Project>
