<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\StockPortfolio.Modules.Alerts.Application\StockPortfolio.Modules.Alerts.Application.csproj" />
  </ItemGroup>

</Project>
